config/routes.rb
Rails.application.routes.draw do
  root 'sweets#index'
  resources :sweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sweet.rb
class Sweet < ApplicationRecord
  def free?
    price.blank? || price.zero?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController
  before_action :fetch_sweet, only: %i[show edit update destroy]

  def index
    @sweets = Sweet.all
  end

  def show; end

  def edit; end

  def update
  return redirect_to @sweet if @sweet.update(sweet_params)
    
	render :edit
  end

  def new
    @sweet = Sweet.new
  end

  def create
    @sweet = Sweet.new(sweet_params)

    return  redirect_to @sweet if @sweet.save
    
    render :new
  end

  def destroy
    @sweet.destroy
    redirect_to sweets_url, status: :see_other
  end

private

  def sweet_params
    params.require(:sweet).
      permit(:name, :description, :origin, :price, :validity)
  end

  def fetch_sweet
    @sweet = Sweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper

  def price(sweet)
    if sweet.free?
      "Free"
    else
      number_to_currency(sweet.price, precision: 0)
    end
  end

  def day_and_time(sweet)
    sweet.validity.strftime("%B %d at %I:%M %P")
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Made with Love</a>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to "Sweet", root_path %>
    <ul>
      <li>
        <%= link_to "All Sweets", sweets_path %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sweetz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <div class="content">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/sweets/_form.html.erb
<%= form_with(model: sweet) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>

  <%= f.label :origin %>
  <%= f.text_field :origin %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :validity %>
  <%= f.datetime_select :validity, {ampm: true}, {class: "datetime"} %>

  <%= f.submit %>
<% end %>

app/views/sweets/_sweet.html.erb
<% @sweets.each do |sweet| %>
  <section class="sweet">
    <div class="summary">
      <h2><%= link_to sweet.name, sweet %></h2>
    <p>  Validity: <%= day_and_time(sweet) %> </p> 
    <p> Origin: <%= sweet.origin %></p>
      <span class="price">
      Price:  <%= price(sweet) %>
      </span>
      <p>
        <%= truncate(sweet.description, length: 35, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>

app/views/sweets/edit.html.erb
<h1>Editing <%= @sweet.name %></h1>

<%= render "form", sweet: @sweet %>

app/views/sweets/index.html.erb
<%= render "sweet", sweet: @sweet %>

app/views/sweets/new.html.erb
<h1>Create a New Sweet</h1>

<%= render "form", sweet: @sweet %>

app/views/sweets/show.html.erb
<section class="sweet-details">
  <div class="details">
    <h1><%= @sweet.name %></h1>
    <h2>
      <%= price(@sweet) %>
    </h2>
    <p> Validity:
      <%= day_and_time(@sweet) %>
    </p>
    <p>
      <%= @sweet.description %>
    </p>
  </div>
</section>

<section class="admin">
  <%= link_to "Edit", edit_sweet_path(@sweet), class: "button" %>
  <%= link_to "Delete", @sweet, class: "button",
        data: { turbo_method: :delete, turbo_confirm: "Really?!" } %>
</section>